# Generated by Django 4.0.2 on 2022-02-16 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название счёта')),
                ('comment', models.CharField(max_length=255, verbose_name='Комментарий')),
                ('value', models.FloatField(verbose_name='Баланс')),
            ],
            options={
                'verbose_name': 'Счёт',
                'verbose_name_plural': 'Счета',
            },
        ),
        migrations.CreateModel(
            name='OperationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Доход'), (1, 'Расход')], verbose_name='Тип')),
                ('description', models.TextField(verbose_name='Описание')),
                ('value', models.FloatField(verbose_name='Сумма')),
                ('repeatability', models.BooleanField(default=False, verbose_name='Повторяемость')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babosiki.operationcategory', verbose_name='Счёт')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babosiki.account', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
            },
        ),
    ]
