# Generated by Django 4.0.2 on 2022-02-16 13:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('babosiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operation',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babosiki.operationcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babosiki.account', verbose_name='Счёт'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='repeatability',
            field=models.BooleanField(default=False, verbose_name='Повторяемый'),
        ),
    ]
