# Generated by Django 4.0.2 on 2022-02-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babosiki', '0002_operation_date_alter_operation_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='type',
            field=models.IntegerField(choices=[(1, 'Доход'), (-1, 'Расход')], verbose_name='Тип'),
        ),
    ]
