# Generated by Django 4.0.2 on 2022-02-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babosiki', '0003_alter_operation_date_alter_operation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueDelta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('value', models.FloatField(verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Дельта баланса',
                'verbose_name_plural': 'Дельты баланса',
            },
        ),
    ]
