# Generated by Django 3.2.24 on 2024-02-15 18:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('babosiki', '0004_alter_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('type', models.IntegerField(choices=[(1, 'Пополнение'), (-1, 'Расход')], verbose_name='Тип')),
                ('description', models.CharField(max_length=128, verbose_name='Описание')),
                ('value', models.FloatField(verbose_name='Сумма')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babosiki.account', verbose_name='Счёт')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babosiki.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
            },
        ),
    ]
