# Generated by Django 4.0.2 on 2022-02-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babosiki', '0004_valuedelta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuedelta',
            name='date',
            field=models.DateField(unique=True, verbose_name='Дата'),
        ),
    ]
