# Generated by Django 4.0.2 on 2022-02-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babosiki', '0005_alter_valuedelta_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('value', models.FloatField(verbose_name='Сумма')),
                ('no_op', models.IntegerField(default=0, verbose_name='Количество операций')),
            ],
            options={
                'verbose_name': 'Дельта баланса',
                'verbose_name_plural': 'Дельты баланса',
            },
        ),
        migrations.DeleteModel(
            name='ValueDelta',
        ),
        migrations.AddField(
            model_name='account',
            name='no_d',
            field=models.IntegerField(default=0, verbose_name='Количество дней'),
        ),
    ]
