# Generated by Django 4.0.2 on 2022-02-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babosiki', '0006_dailyexpenses_delete_valuedelta_account_no_d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
