# Generated by Django 3.2.24 on 2024-05-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babosiki', '0008_alter_operation_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operation',
            options={'ordering': ['date'], 'verbose_name': 'Операция', 'verbose_name_plural': 'Операции'},
        ),
        migrations.AlterField(
            model_name='operation',
            name='type',
            field=models.IntegerField(choices=[(-1, 'Расход'), (1, 'Пополнение')], verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма'),
        ),
    ]
