# Generated by Django 4.0.2 on 2022-02-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babosiki', '0008_historicaloperationcategory_historicaloperation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='initial_value',
            field=models.FloatField(default=0, verbose_name='Начальный баланс'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='initial_value',
            field=models.FloatField(default=0, verbose_name='Начальный баланс'),
            preserve_default=False,
        ),
    ]
