# Generated by Django 4.0.2 on 2022-02-16 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babosiki', '0009_account_initial_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyexpenses',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='babosiki.account', verbose_name='Счёт'),
        ),
        migrations.AddField(
            model_name='historicaldailyexpenses',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='babosiki.account', verbose_name='Счёт'),
        ),
        migrations.AlterField(
            model_name='historicaloperation',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='babosiki.account', verbose_name='Счёт'),
        ),
        migrations.AlterField(
            model_name='historicaloperation',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='babosiki.operationcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babosiki.account', verbose_name='Счёт'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babosiki.operationcategory', verbose_name='Категория'),
        ),
    ]
