# Generated by Django 3.2.24 on 2024-05-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babosiki', '0010_alter_account_initial_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Начальный баланс'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Сумма'),
        ),
    ]
