# Generated by Django 4.0.2 on 2022-02-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babosiki', '0010_dailyexpenses_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyexpenses',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='historicaldailyexpenses',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyexpenses',
            unique_together={('date', 'account')},
        ),
    ]
