# Generated by Django 4.0.2 on 2022-02-16 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babosiki', '0011_alter_dailyexpenses_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='operation',
            unique_together={('date', 'description', 'value', 'account')},
        ),
    ]
