# Generated by Django 3.2.24 on 2024-02-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babosiki', '0003_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.IntegerField(choices=[(1, 'Дебетовый'), (-1, 'Кредитный')], verbose_name='Тип'),
        ),
    ]
